swagger: '2.0'
info:
  description: Foro de Sistale API para desarrolladores
  version: 1.0.0
  title: Foro de Sistale API
host: localhost:3000
basePath: /
schemes:
  - http

securityDefinitions:
  Bearer:
    type: apiKey
    name: authorization
    in: header
    
paths:
  /v1/login:
    post:
      tags:
        - Cuenta
      summary: Autenticación de usuario
      description: Permite a un usuario autenticarse en la aplicación.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Credenciales
          description: Iniciar sesión
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Autenticación exitosa
        '401':
          description: Credenciales inválidas
  /v1/register:
    post:
      tags:
        - Cuenta
      summary: Registro de usuario
      description: Permite a un usuario registrarse en la aplicación.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Credenciales
          description: Registrarse
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Registro exitoso
        '401':
          description: Datos inválidos
  /v1/articulo:
    post:
      tags:
        - Artículo
      security:
        - Bearer: []
      summary: Crear un nuevo artículo
      description: Permite la creación de un nuevo artículo.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: articulo
          description: Datos del nuevo articulo
          required: true
          schema:
            type: object
            properties:
              titulo:
                type: string
              contenido:
                type: string
      responses:
        '201':
          description: Articulo creado exitosamente
        '400':
          description: Datos inválidos
  /v1/articulo/{idArticulo}:
    get:
      tags:
        - Artículo
      security:
        - Bearer: []
      summary: Leer un artículo específico
      description: Obtiene los detalles de un artículo específico.
      produces:
        - application/json
      parameters:
        - name: idArticulo
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Articulo encontrado
        '404':
          description: Articulo no encontrado
    patch:
      tags:
        - Artículo
      security:
        - Bearer: []
      summary: Editar un artículo existente
      description: Permite editar un artículo existente.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: idArticulo
          in: path
          required: true
          type: integer
        - in: body
          name: articulo
          required: true
          schema:
            type: object
            properties:
              titulo:
                type: string
              contenido:
                type: string
      responses:
        '200':
          description: Artículo actualizado exitosamente
        '404':
          description: Artículo no encontrada
    delete:
      tags:
        - Artículo
      security:
        - Bearer: []
      summary: Eliminar un artículo
      description: Permite la eliminación de un artículo.
      produces:
        - application/json
      parameters:
        - name: idArticulo
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Artículo eliminado exitosamente
        '404':
          description: Artículo no encontrada
  /v1/articulos:
    get:
      tags:
        - Artículo
      security:
        - Bearer: []
      summary: Listar todos los artículos
      description: Recupera todos los articulos disponibles.
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          description: Número de página para la paginación
          required: false
          type: integer
        - name: size
          in: query
          description: Tamaño de la página para la paginación
          required: false
          type: integer
      responses:
        '200':
          description: Articulos listados exitosamente
          schema:
            type: object
            properties:
              total:
                type: integer
                description: Total de artículos disponibles.
              items:
                type: array
                items:
                  $ref: '#/definitions/Articulo'
        '404':
          description: No se encontraron articulos
  /v1/comentario:
    post:
      tags:
        - Comentario
      security:
        - Bearer: []
      summary: Crear un nuevo comentario
      description: Permite la creación de un nuevo comentario.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: articulo
          description: contenido del comentario
          required: true
          schema:
            type: object
            properties:
              contenido:
                type: string
      responses:
        '201':
          description: Comentario creado exitosamente
        '400':
          description: Datos inválidos
  /v1/comentario/{idComentario}:
    get:
      tags:
        - Comentario
      security:
        - Bearer: []
      summary: Leer un comentario específico
      description: Obtiene los detalles de un comentario específico.
      produces:
        - application/json
      parameters:
        - name: idComentario
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Comentario encontrado
        '404':
          description: Comentario no encontrado
    patch:
      tags:
        - Comentario
      security:
        - Bearer: []
      summary: Editar un comentario existente
      description: Permite editar un comentario existente.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: idComentario
          in: path
          required: true
          type: integer
        - in: body
          name: comentario
          required: true
          schema:
            type: object
            properties:
              contenido:
                type: string
      responses:
        '200':
          description: Comentario actualizado exitosamente
        '404':
          description: Comentario no encontrado
    delete:
      tags:
        - Comentario
      security:
        - Bearer: []
      summary: Eliminar un comentario
      description: Permite la eliminación de un comentario.
      produces:
        - application/json
      parameters:
        - name: idComentario
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Comentario eliminado exitosamente
        '404':
          description: Comentario no encontrado
  /v1/comentarios:
    get:
      tags:
        - Comentario
      security:
        - Bearer: []
      summary: Listar todos los comentarios
      description: Recupera todos los comentarios disponibles.
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          description: Número de página para la paginación
          required: false
          type: integer
        - name: size
          in: query
          description: Tamaño de la página para la paginación
          required: false
          type: integer
      responses:
        '200':
          description: Comentarios listados exitosamente
          schema:
            type: object
            properties:
              total:
                type: integer
                description: Total de comentarios disponibles.
              items:
                type: array
                items:
                  $ref: '#/definitions/Comentario'
        '404':
          description: No se encontraron comentarios
definitions:
  Articulo:
    type: object
    properties:
      id:
        type: integer
      titulo:
        type: string
      contenido:
        type: string

  Comentario:
    type: object
    properties:
      id:
        type: integer
      contenido:
        type: string