import type { Metadata } from "next"
import { Inter } from "next/font/google"
import CrushBubble from 'next/font/local'
import "./globals.css"
import Header from "@/components/page-header"
import Footer from "@/components/page-footer"

const inter = Inter({ subsets: ["latin"] })

const fontCrushBubble = CrushBubble({
  src: '../../public/fonts/CrushBubble.otf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return ( 
    <html lang="en" className="h-full m-0 p-0">
      <body className={`${fontCrushBubble.className} bg-[#F1FFCF] flex flex-col h-screen m-0 p-0`}>
          <Header />      
          <main className="flex-1 w-full overflow-auto bg-[#F8df82]">{children}</main>
          <Footer />
      </body>
    </html>
  )
}
